<?php
add_action('wp_enqueue_scripts', function() {
    // Helper function to enqueue styles and scripts
    function enqueue_if_exists($name, $file, $is_css = true) {
        if(locate_template($file)) {
            if($is_css) {
                wp_enqueue_style($name, get_template_directory_uri() . '/' . $file);
            } else {
                wp_enqueue_script($name,get_template_directory_uri() . '/' . $file);
            }
        }
    }

    // We don't need to load jQuery since it's VERY likely that it's within the
    // assets/vendor/vendor.js
    //wp_deregister_script('jquery');

    // Vendor file generated by Grunt
    enqueue_if_exists('vendor-js', 'assets/vendor/vendor.js', false);

    // Vendor styles generated by Grunt
    enqueue_if_exists('vendor-css', 'assets/vendor/vendor.css');


    // Our very own styles
    wp_enqueue_style('theme-style', get_stylesheet_uri());

    // Our very own SASS
    wp_enqueue_style('additional-css', get_template_directory_uri() .'/style.ext.css', array(), 'v1.0');

    // Load assets from functions.php
    global $assets;
    foreach($assets as $name => $asset) {
        $exp = explode('.', $asset);
        if($exp[1] == 'js') {
            enqueue_if_exists($name, $asset, false);
        } elseif($exp[0] == 'css') {
            enqueue_if_exists($name, $asset);
        } else {
            trigger_error('Unknown asset (' . $name . ')', E_USER_ERROR);
        }
    }
});
